version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: humanresources-postgres
    environment:
      POSTGRES_DB: humanresources
      POSTGRES_USER: hruser
      POSTGRES_PASSWORD: hrpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: